name: Update Copr
on:
  # Disabled: vendor provides official RPM. Keep manual dispatch only if you ever
  # need a one-off archival build.
  # schedule:
  #   - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  Update-Cursor:
    # Hard stop: job is disabled. Flip to `true` only for a one-off run.
    if: ${{ false }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Guard
        run: |
          echo "Disabled. Vendor provides official RPM. See README for migration."
          exit 0
      - name: Check out repository code
        if: ${{ false }}
        uses: actions/checkout@v4

      - name: Check latest version, update spec, build, and release
        if: ${{ false }}
        env:
          COPR_CONFIG: ${{ secrets.COPR_CONFIG }}
        run: |
          echo "Workflow disabled."
          exit 0
